In [2]:
import edgar
import pandas as pd
import requests
import re
from bs4 import BeautifulSoup as bsoup
import numpy as np

## Get the annual filings for each company

In [5]:
comp_2016 = pd.DataFrame.from_csv('companies_2016.csv',encoding='latin-1')
comp_2016 = comp_2016[:505]
comp_2016.CIK = comp_2016['CIK'].astype(int).apply(lambda x: str(x).zfill(10))

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.

In [12]:
res = requests.get('http://siblisresearch.com/data/market-caps-sp-100-us/')
soup = bsoup(res.content,'html.parser')

In [38]:
def extractTable(soup): 
    table = []
    for div in soup.find_all('table', {'id':'supsystic-table-8'}):
        #for a in div.find_all('a', {'data-tn-element':'jobTitle'}):
            table+=div
    return(table)

In [39]:
tab = extractTable(soup)

In [34]:
print(type(tab))
tab
for i in tab:
    print(i.text)

<class 'list'>
 Ticker  Company Name  9/30/2018  12/31/2017  12/31/2016  12/31/2015  12/31/2014  12/31/2013  AAPL  Apple Inc.  1,093,240.08  859,967.80  617,588.49  586,859.34  647,361.04  500,738.96  AMZN  Amazon.com Inc.  975,461.00  566,023.48  356,313.48  316,831.55  143,693.91  182,539.74  MSFT  Microsoft Corp.  878,018.49  659,085.70  483,160.31  443,169.41  382,880.52  312,297.48  GOOGL  Alphabet Inc. Class A  840,062.50  731,884.41  546,188.24  534,763.62  360,940.07  376,370.28  BRK.B  Berkshire Hathaway Inc  528,336.12  489,062.06  401,987.01  325,490.35  370,024.10  292,360.78  FB  Facebook Inc.  475,453.86  512,792.76  332,724.60  297,757.70  218,221.94  139,193.55  JPM  JPMorgan Chase & Co.  379,242.15  366,301.48  308,768.40  243,065.01  233,935.87  219,837.37  JNJ  Johnson & Johnson  370,613.53  374,802.39  313,432.49  284,220.49  292,702.93  258,415.51  XOM  Exxon Mobil Corp.  359,958.53  354,549.96  374,280.51  324,501.10  391,482.21  442,093.62  V  Visa Inc.  344,137.61  257,324.21  181,084.42  186,817.95  161,506.02  141,189.59  BAC  Bank of America Corp.  294,974.70  303,681.16  225,526.06  175,242.04  188,139.29  166,071.71  WMT  Wal-Mart Stores Inc  275,625.85  293,090.00  212,418.89  196,276.04  276,807.56  254,622.90  PFE  Pfizer Inc.  258,343.19  216,559.38  197,100.17  199,280.68  196,265.47  198,515.20  UNH  United Health Group Inc.  255,930.48  213,625.74  152,328.63  112,123.63  97,025.27  75,808.88  WFC  Wells Fargo  254,867.01  296,774.40  276,779.12  277,660.71  284,385.55  239,148.99  T  AT&T Inc.  243,782.57  238,700.84  261,176.73  211,690.32  174,231.33  185,222.88  HD  Home Depot  237,186.75  221,371.04  163,331.03  167,677.26  138,332.30  115,953.41  CVX  Chevron Corp.  234,306.46  238,449.64  222,190.41  169,308.05  212,067.76  240,223.54  MA  Mastercard Inc.  231,291.79  159,533.44  110,425.36  107,118.78  95,889.19  96,747.10  CSCO  Cisco Systems  224,471.10  189,340.72  151,697.12  137,866.31  142,260.02  119,924.64  VZ  Verizon Communications  220,604.06  215,926.66  217,610.72  188,063.31  194,124.09  140,540.40  INTC  Intel Corp.  218,054.19  216,351.92  171,883.53  162,569.55  175,462.15  129,047.16  BA  Boeing Co.  214,171.26  174,303.31  96,080.40  96,872.99  92,666.64  102,565.82  PG  Procter & Gamble  207,908.54  231,629.85  224,997.49  216,040.70  246,136.02  221,291.19  ORCL  Oracle Corp.  196,495.16  195,881.04  157,735.47  153,470.57  197,479.77  172,070.87  KO  The Coca Cola Co.  196,446.07  195,402.92  178,815.28  186,832.40  184,928.37  182,421.78  MRK  Merck & Co.  189,412.78  151,738.36  162,312.71  147,554.94  161,901.08  146,242.55  C  Citigroup Inc.  180,541.24  191,226.93  169,359.45  154,162.73  163,925.60  158,049.68  DIS  The Walt Disney Co.  175,410.00  161,265.00  165,862.07  173,715.94  159,719.02  134,256.19  NVDA  Nvidia Corp.  170,860.16  113,197.50  57,532.86  17,732.48  10,897.92  9,107.95  NFLX  Netflix Inc.  162,917.90  83,194.12  53,128.15  48,884.64  20,580.64  21,817.02  CMCSA  Comcast Class A Comm.  162,246.25  186,012.55  164,572.94  137,824.54  147,407.30  135,462.35  PEP  PepsiCo Inc.  158,121.20  170,286.40  150,058.57  145,568.55  141,519.06  127,196.78  DWDP  DowDuPont Inc  148,369.22  165,752.66  69,301.03  57,500.17  52,797.86  53,513.23  ABBV  AbbVie Inc.  143,206.23  153,974.99  101,763.70  96,842.41  104,263.26  84,013.42  IBM  IBM Corp.  138,019.65  141,480.70  157,832.42  133,506.54  158,781.05  203,673.63  NKE  Nike Inc.  135,599.02  101,581.20  84,174.48  106,687.50  83,073.60  69,832.32  AMGN  Amgen Inc.  134,531.21  125,590.58  108,768.84  122,450.06  121,167.12  86,030.69  MDT  Medtronic Inc.  132,969.58  109,302.55  97,802.14  108,161.52  71,067.69  57,295.31  ADBE  Adobe Systems Inc.  132,007.44  86,088.75  50,883.45  46,764.18  36,258.33  29,933.23  MCD  McDonald's Corp.  129,783.58  136,680.49  101,081.64  108,479.69  91,189.21  96,547.76  ABT  Abbott Laboratories  128,696.84  99,507.42  56,551.43  66,993.15  67,790.71  59,265.31  PM  Philip Morris Int'l  126,753.44  164,097.48  141,933.01  136,198.61  126,550.09  139,596.72  MMM  3M Company  123,605.23  140,017.85  107,403.78  92,751.01  104,514.09  93,300.19  HON  Honeywell Int'l Inc.  122,196.64  115,158.02  88,292.18  79,820.47  78,218.38  71,695.57  UNP  Union Pacific  120,406.27  104,721.10  85,443.93  66,792.26  105,918.36  77,375.59  CRM  Salesforce.com  120,338.00  73,840.73  46,490.78  52,057.60  37,424.61  33,279.57  LLY  Eli Lilly and Co.  118,041.86  92,906.68  81,195.38  93,366.57  76,815.54  57,459.15  MO  Altria Group Inc.  113,760.16  135,768.91  131,877.33  114,131.12  97,380.68  76,780.58  UTX  United Technologies  111,861.00  101,945.01  90,261.77  85,216.11  104,840.67  104,420.83  ACN  Accenture plc  108,910.98  97,454.49  75,216.79  67,773.58  58,404.99  54,547.21  QCOM  Qualcomm, Inc.  105,812.07  94,774.25  96,293.03  75,139.67  123,581.13  125,440.62  TXN  Texas Instruments  104,539.73  102,681.13  72,932.49  55,599.92  56,480.36  48,062.26  PYPL  PayPal Holdings Inc.  104,002.56  88,344.00  47,626.32  44,225.18  COST  Costco Co.  103,018.84  81,741.11  70,326.72  71,023.99  62,441.44  52,335.71  AVGO  Broadcom Inc  101,899.49  105,003.25  70,527.69  40,132.52  25,683.85  BMY  Bristol-Myers Squibb  101,306.92  99,580.00  97,666.68  114,761.39  97,917.55  87,513.76  UPS  United Parcel Service  100,405.00  102,469.00  99,507.52  85,259.78  100,608.85  96,988.84  GILD  Gilead Sciences  100,064.16  93,705.12  94,343.02  145,833.00  142,206.67  115,154.51  LMT  Lockheed Martin Corp.  98,522.83  91,499.25  73,226.67  66,729.11  60,837.68  47,616.84  TMO  Thermo Fisher Scientific  98,314.45  76,201.69  55,738.03  56,612.05  50,119.13  40,238.22  GE  General Electric  98,122.30  151,475.96  279,545.92  293,989.71  253,766.19  283,589.85  BKNG  Booking Holdings  94,763.78  84,231.73  72,342.73  63,472.11  59,696.83  59,779.91  LOW  Lowe's Cos.  93,119.02  77,233.14  61,863.52  69,584.58  66,936.14  51,820.83  AXP  American Express Co  91,687.89  85,307.29  67,802.09  68,454.31  96,266.35  97,196.42  CAT  Caterpillar Inc.  90,628.62  94,173.91  54,259.67  39,568.62  55,412.17  57,787.49  COP  ConocoPhillips  89,946.15  64,611.40  62,124.81  57,645.43  85,006.85  86,553.24  USB  U.S. Bancorp  86,401.49  88,709.51  87,312.36  74,637.38  80,432.90  73,782.72  FOXA  Twenty-First Century Fox  85,828.78  63,967.86  51,897.40  52,452.17  81,881.90  79,768.80  GS  Goldman Sachs Group  84,735.59  95,486.34  95,217.05  76,874.58  84,421.88  80,339.73  SLB  Schlumberger Ltd.  84,320.53  93,263.24  116,800.31  87,962.00  109,905.08  118,670.82  MS  Morgan Stanley  81,481.34  93,820.92  79,126.69  61,591.29  75,947.24  61,194.02  CVS  CVS Health Corp.  80,058.24  73,515.00  84,152.70  108,262.38  110,408.15  85,186.48  NEE  NextEra Energy  79,041.00  73,565.49  55,819.84  47,845.09  46,393.67  37,260.28  SBUX  Starbucks Corp.  77,660.49  80,838.47  80,803.81  89,132.54  61,398.02  59,074.70  DHR  Danaher Corp.  76,029.40  64,658.41  53,842.08  63,649.27  60,227.73  53,823.84  BLK  BlackRock Inc  75,780.44  82,731.45  61,673.74  55,842.90  59,073.92  52,878.97  CHTR  Charter Communications  75,559.84  80,128.48  77,929.87  EOG  EOG Resources  73,886.89  62,423.45  58,279.90  38,913.76  50,455.19  45,816.12  WBA  Walgreens Boots Alliance  72,346.83  71,926.19  89,331.97  91,866.09  72,057.92  54,577.82  ANTM  Anthem Inc.  71,289.45  57,621.69  37,874.05  36,403.60  33,923.49  27,293.58  BIIB  Biogen Idec, Inc.  71,171.83  67,377.56  61,699.63  68,286.33  80,162.81  66,038.07  BDX  Becton Dickinson & Co  69,834.20  56,991.98  35,300.56  32,692.66  26,911.04  21,432.52  TJX  TJX Companies Inc.  69,538.32  48,345.89  48,977.32  47,476.30  47,244.76  45,324.71  KHC  Kraft Heinz Co  67,179.09  94,789.44  106,292.02  88,291.06  36,802.22  32,142.97  SYK  Stryker Corp.  66,450.54  57,972.10  44,863.09  34,945.44  35,687.02  28,434.40  AET  Aetna Inc.  66,413.09  58,951.45  43,515.11  37,701.44  31,241.51  25,206.83  SCHW  Charles Schwab Corp.  66,400.42  69,109.76  52,324.27  43,353.10  39,421.17  33,519.64  ADP  ADP, LLC.  66,109.61  51,880.01  46,371.56  39,073.46  40,189.09  38,899.14  ISRG  Intuitive Surgical Inc.  65,263.80  40,982.76  24,572.18  20,407.27  19,175.13  14,619.62  AGN  Allergan, Plc  64,629.86  54,014.12  70,332.35  123,193.44  68,229.35  29,240.06  AMT  American Tower Corp.  64,104.33  61,179.75  44,992.52  41,065.11  39,190.37  31,500.16  CSX  CSX Corp.  63,594.95  48,958.90  33,654.23  25,299.82  36,063.23  29,163.40  FDX  FedEx Corporation  63,452.02  66,849.27  49,623.98  41,063.88  49,200.14  44,889.02  ATVI  Activision Blizzard Inc  63,404.59  47,965.22  26,837.42  28,304.13  PNC  PNC Financial SVCS Group Inc  63,328.35  68,249.17  56,901.27  48,398.99  48,006.14  41,280.94  MDLZ  Mondelez Int'l  62,994.91  63,692.22  68,463.78  71,258.25  61,031.60  61,908.72  CELG  Celgene Corp.  62,875.67  79,240.55  89,729.75  94,090.04  89,343.03  69,627.47  OXY  Occidental Petroleum  62,837.12  56,357.63  54,433.11  51,636.19  62,507.25  76,656.31  CB  Chubb Ltd.  61,942.41  67,779.92  61,480.59  37,880.55  38,110.06  35,224.32

In [50]:
# tab = ''.join(tab)
df = pd.read_html('http://siblisresearch.com/data/market-caps-sp-100-us/')[0]

In [59]:
# create a dataframe from 2016 and sort the companies
df_2016 = pd.DataFrame(df['Company Name'])
df_2016['12/31/2016'] = df['12/31/2016']
df_2016 = df_2016.sort_values(by=['12/31/2016'], ascending=False)
df_2016

                    Company Name  12/31/2016
0                     Apple Inc.   617588.49
3          Alphabet Inc. Class A   546188.24
2                Microsoft Corp.   483160.31
4         Berkshire Hathaway Inc   401987.01
8              Exxon Mobil Corp.   374280.51
1                Amazon.com Inc.   356313.48
5                  Facebook Inc.   332724.60
7              Johnson & Johnson   313432.49
6           JPMorgan Chase & Co.   308768.40
61              General Electric   279545.92
14                   Wells Fargo   276779.12
15                     AT&T Inc.   261176.73
10         Bank of America Corp.   225526.06
23              Procter & Gamble   224997.49
17                 Chevron Corp.   222190.41
20        Verizon Communications   217610.72
11           Wal-Mart Stores Inc   212418.89
12                   Pfizer Inc.   197100.17
9                      Visa Inc.   181084.42
25             The Coca Cola Co.   178815.28
21                   Intel Corp.   171883.53
27                Citigroup Inc.   169359.45
28           The Walt Disney Co.   165862.07
31         Comcast Class A Comm.   164572.94
16                    Home Depot   163331.03
26                   Merck & Co.   162312.71
35                     IBM Corp.   157832.42
24                  Oracle Corp.   157735.47
13      United Health Group Inc.   152328.63
19                 Cisco Systems   151697.12
..                           ...         ...
63                   Lowe's Cos.    61863.52
81             Biogen Idec, Inc.    61699.63
76                 BlackRock Inc    61673.74
99                    Chubb Ltd.    61480.59
78                 EOG Resources    58279.90
29                  Nvidia Corp.    57532.86
95  PNC Financial SVCS Group Inc    56901.27
41           Abbott Laboratories    56551.43
73                NextEra Energy    55819.84
60      Thermo Fisher Scientific    55738.03
98          Occidental Petroleum    54433.11
65              Caterpillar Inc.    54259.67
75                 Danaher Corp.    53842.08
30                  Netflix Inc.    53128.15
87          Charles Schwab Corp.    52324.27
68      Twenty-First Century Fox    51897.40
39            Adobe Systems Inc.    50883.45
93             FedEx Corporation    49623.98
83            TJX Companies Inc.    48977.32
53          PayPal Holdings Inc.    47626.32
46                Salesforce.com    46490.78
88                     ADP, LLC.    46371.56
91          American Tower Corp.    44992.52
85                 Stryker Corp.    44863.09
86                    Aetna Inc.    43515.11
80                   Anthem Inc.    37874.05
82         Becton Dickinson & Co    35300.56
92                     CSX Corp.    33654.23
94       Activision Blizzard Inc    26837.42
89       Intuitive Surgical Inc.    24572.18

[100 rows x 2 columns]

In [69]:
comp_2016

,2018,Unnamed: 2,Security,Symbol,SEC filings,GICS Sector,GICS Sub Industry,Headquarters Location,Date first added,CIK,Founded,Unnamed: 12,Unnamed: 13
2017,,,,,,,,,,,,,
NaN,NaN,0,3M Company,MMM,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,0000066740,1902,NaN,NaN
NaN,NaN,1,Abbott Laboratories,ABT,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",3/31/64,0000001800,1888,NaN,NaN
NaN,NaN,2,AbbVie Inc.,ABBV,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",12/31/12,0001551152,2013 (1888),NaN,NaN
NaN,ABMD,3,Wyndam Worldwide,WYN,reports,NaN,NaN,NaN,NaN,0001361658,NaN,NaN,NaN
NaN,NaN,4,Accenture plc,ACN,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",7/6/11,0001467373,1989,NaN,NaN
NaN,NaN,5,Activision Blizzard,ATVI,reports,Communication Services,Interactive Home Entertainment,"Santa Monica, California",8/31/15,0000718877,2008,NaN,NaN
NaN,NaN,6,Adobe Systems Inc,ADBE,reports,Information Technology,Application Software,"San Jose, California",5/5/97,0000796343,1982,NaN,NaN
AMD,NaN,7,Urban Outfilers,URBN,NaN,NaN,NaN,NaN,NaN,0000912615,NaN,NaN,NaN
NaN,NaN,8,Advance Auto Parts,AAP,reports,Consumer Discretionary,Automotive Retail,"Roanoke, Virginia",7/9/15,0001158449,1932,NaN,NaN
NaN,NaN,9,AES Corp,AES,reports,Utilities,Independent Power Producers & Energy Traders,"Arlington, Virginia",10/2/98,0000874761,1981,NaN,NaN
NaN,NaN,10,Affiliated Managers Group Inc,AMG,reports,Financials,Asset Management & Custody Banks,"Beverly, Massachusetts",7/1/14,0001004434,1993,NaN,NaN
NaN,NaN,11,AFLAC Inc,AFL,reports,Financials,Life & Health Insurance,"Columbus, Georgia",5/28/99,0000004977,1955,NaN,NaN
NaN,NaN,12,Agilent Technologies Inc,A,reports,Health Care,Health Care Equipment,"Santa Clara, California",6/5/00,0001090872,1999,NaN,NaN
NaN,NaN,13,Air Products & Chemicals Inc,APD,reports,Materials,Industrial Gases,"Allentown, Pennsylvania",4/30/85,0000002969,1940,NaN,NaN
NaN,NaN,14,Akamai Technologies Inc,AKAM,reports,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",7/12/07,0001086222,1998,NaN,NaN
NaN,NaN,15,Alaska Air Group Inc,ALK,reports,Industrials,Airlines,"Seattle, Washington",5/13/16,0000766421,1985,NaN,NaN
NaN,NaN,16,Albemarle Corp,ALB,reports,Materials,Specialty Chemicals,"Baton Rouge, Louisiana",7/1/16,0000915913,1994,NaN,NaN
ARE,NaN,17,First Solar,FSLR,reports,NaN,NaN,NaN,NaN,0001274494,NaN,NaN,NaN
NaN,NaN,18,Alexion Pharmaceuticals,ALXN,reports,Health Care,Biotechnology,"Cheshire, Connecticut",5/25/12,0000899866,1992,NaN,NaN
ALGN,NaN,19,Terdata Corp.,TDC,reports,NaN,NaN,NaN,NaN,0000816761,NaN,NaN,NaN
NaN,NaN,20,Allegion,ALLE,reports,Industrials,Building Products,"Dublin, Ireland",12/2/13,0001579241,1908,NaN,NaN
NaN,NaN,21,"Allergan, Plc",AGN,reports,Health Care,Pharmaceuticals,"Dublin, Ireland",4/12/99,0001578845,1983,NaN,NaN
NaN,NaN,22,Alliance Data Systems,ADS,reports,Information Technology,Data Processing & Outsourced Services,"Plano, Texas",12/23/13,0001101215,1996,NaN,NaN
NaN,NaN,23,Alliant Energy Corp,LNT,reports,Utilities,Electric Utilities,"Madison, Wisconsin",7/1/16,0000352541,1917,NaN,NaN
NaN,NaN,24,Allstate Corp,ALL,reports,Financials,Property & Casualty Insurance,"Northfield Township, Illinois",7/13/95,0000899051,1931,NaN,NaN
NaN,NaN,25,Alphabet Inc Class A,GOOGL,reports,Communication Services,Interactive Media & Services,"Mountain View, California",4/3/14,0001652044,1998,NaN,NaN
NaN,NaN,26,Alphabet Inc Class C,GOOG,reports,Communication Services,Interactive Media & Services,"Mountain View, California",4/3/06,0001652044,1998,NaN,NaN
NaN,NaN,27,Altria Group Inc,MO,reports,Consumer Staples,Tobacco,"Richmond, Virginia",NaN,0000764180,1985,NaN,NaN
NaN,NaN,28,Amazon.com Inc.,AMZN,reports,Consumer Discretionary,Internet & Direct Marketing Retail,"Seattle, Washington",11/18/05,0001018724,1994,NaN,NaN
NaN,NaN,29,Ameren Corp,AEE,reports,Utilities,Multi-Utilities,"St. Louis, Missouri",9/19/91,0001002910,1902,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,475,Viacom Inc.,VIAB,reports,Communication Services,Movies & Entertainment,"New York, New York",NaN,0001339947,NaN,NaN,NaN
NaN,NaN,476,Visa Inc.,V,reports,Information Technology,IT Services,"San Francisco, California",40168,0001403161,NaN,NaN,NaN
NaN,NaN,477,Vornado Realty Trust,VNO,reports,Real Estate,Office REITs,"New York, New York",NaN,0000899689,NaN,NaN,NaN
NaN,NaN,478,Vulcan Materials,VMC,reports,Materials,Construction Materials,"Birmingham, Alabama",36341,0001396009,NaN,NaN,NaN
NaN,WAB,479,The Goodyear Tire & Rubber Company,GT,reports,NaN,NaN,NaN,NaN,0000042582,NaN,NaN,NaN
NaN,NaN,480,Walmart,WMT,reports,Consumer Staples,Hypermarkets & Super Centers,"Bentonville, Arkansas",30194,0000104169,NaN,NaN,NaN
NaN,NaN,481,Walgreens Boots Alliance,WBA,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",29220,0001618921,NaN,NaN,NaN
NaN,NaN,482,The Walt Disney Company,DIS,reports,Communication Services,Movies & Entertainment,"Burbank, California",27941,0001001039,NaN,NaN,NaN
NaN,NaN,483,Waste Management Inc.,WM,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,0000823768,1968,NaN,NaN
NaN,NaN,484,Waters Corporation,WAT,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,0001000697,1958,NaN,NaN
NaN,NaN,485,Wec Energy Group Inc,WEC,reports,Utilities,Electric Utilities,"Milwaukee, Wisconsin",39752,0000783325,NaN,NaN,NaN
NaN,wcg,486,XL Group,XL,reports,NaN,NaN,NaN,NaN,0000875159,NaN,NaN,NaN
NaN,NaN,487,Wells Fargo,WFC,reports,Financials,Diversified Banks,"San Francisco, California",27941,0000072971,NaN,NaN,NaN
NaN,NaN,488,Welltower Inc.,WELL,reports,Real Estate,Health Care REITs,"Toledo, Ohio",39843,0000766704,NaN,NaN,NaN
NaN,NaN,489,Western Digital,WDC,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Irvine, California",39995,0000106040,NaN,NaN,NaN
NaN,NaN,490,Western Union Co,WU,reports,Information Technology,Internet Software & Services,"Englewood, Colorado",NaN,0001365135,1851,NaN,NaN
NaN,NaN,491,WestRock,WRK,reports,Materials,Paper Packaging,"Richmond, Virginia",NaN,0001636023,NaN,NaN,NaN
NaN,NaN,492,Weyerhaeuser,WY,reports,Real Estate,Specialized REITS,"Federal Way, Washington",NaN,0000106535,NaN,NaN,NaN
NaN,NaN,493,Whirlpool Corp.,WHR,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,0000106640,1911,NaN,NaN
NaN,NaN,494,Williams Cos.,WMB,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",27484,0000107263,NaN,NaN,NaN
NaN,NaN,495,Willis Towers Watson,WLTW,reports,Financials,Insurance Brokers,"London, United Kingdom",42374,0001140536,NaN,NaN,NaN
NaN,NaN,496,Wynn Resorts Ltd,WYNN,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",39766,0001174922,NaN,NaN,NaN
NaN,NaN,497,Xcel Energy Inc,XEL,reports,Utilities,Multi-Utilities,"Minneapolis, Minnesota",NaN,0000072903,1909,NaN,NaN
NaN,NaN,498,Xerox,XRX,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,0000108772,1906,NaN,NaN
NaN,NaN,499,Xilinx,XLNX,reports,Information Technology,Semiconductors,"San Jose, California",36472,0000743988,NaN,NaN,NaN
NaN,NaN,500,Xylem Inc.,XYL,reports,Industrials,Industrial Machinery,"White Plains, New York",40848,0001524472,NaN,NaN,NaN
NaN,NaN,501,Yum! Brands Inc,YUM,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",35709,0001041061,NaN,NaN,NaN
NaN,NaN,502,Zimmer Biomet Holdings,ZBH,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",37110,0001136869,NaN,NaN,NaN
NaN,NaN,503,Zions Bancorp,ZION,reports,Financials,Regional Banks,"Salt Lake City, Utah",37064,0000109380,NaN,NaN,NaN
NaN,NaN,504,Zoetis,ZTS,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",41446,0001555280,NaN,NaN,NaN

In [70]:
df_2016_top = df_2016.nlargest(25,columns='12/31/2016')

In [81]:
df_2016_top['Company Name']

0                 Apple Inc.
3      Alphabet Inc. Class A
2            Microsoft Corp.
4     Berkshire Hathaway Inc
8          Exxon Mobil Corp.
1            Amazon.com Inc.
5              Facebook Inc.
7          Johnson & Johnson
6       JPMorgan Chase & Co.
61          General Electric
14               Wells Fargo
15                 AT&T Inc.
10     Bank of America Corp.
23          Procter & Gamble
17             Chevron Corp.
20    Verizon Communications
11       Wal-Mart Stores Inc
12               Pfizer Inc.
9                  Visa Inc.
25         The Coca Cola Co.
21               Intel Corp.
27            Citigroup Inc.
28       The Walt Disney Co.
31     Comcast Class A Comm.
16                Home Depot
Name: Company Name, dtype: object

In [68]:
df_2016_top.reset_index(drop=True, inplace=True)

In [94]:
from collections import defaultdict
cikDict = defaultdict
for i in range(len(df_2016_top)):
    for j in range(len(comp_2016['Security'])):
        
        if df_2016_top['Company Name'][i] == comp_2016['Security'][j]:
            cikDict[i] += comp_2016['CIK'][j]
#         else:
#             cikDict += None
# for comp in df_2016_top['Company Name']:
#     if comp in comp_2016['Security']:
#         cikDict +=

TypeError: 'type' object is not subscriptable

In [91]:
comp_2016['CIK'][1]

'0000001800'

In [32]:
data1 = pd.read_html(tab,skiprows=1)[0]

TypeError: Cannot read object of type 'list'

In [6]:
comp = comp_2016[:50]

In [7]:
company = edgar.Company('ATVI','0000718877')
tree = company.getAllFilings(filingType = "10-K")
doc = edgar.getDocuments(tree, noOfDocuments=3)

## 2016

In [9]:
def annual_filings(name,ID):
    '''This function finds the correct document'''
    # get filings from package
    company = edgar.Company(name,ID)
    tree = company.getAllFilings(filingType = "10-K")
    doc = edgar.getDocuments(tree, noOfDocuments=4)
    
    # if compnay only has one document
    #if len(doc) > 3:
        #return None
    
    # search for the right document year 
    d = 1
    while d < len(doc):
    
        filing = (re.sub('\\xa0|\\n',' ',doc[d]))
        filingShort = filing[:1000]
        # see if the document is amended
        if '10-K/A' in filing[1:15]:
            d += 1
    
        # if in the right fiscal year and remove the new lines and break
        elif re.search(r'FOR THE FISCAL YEAR ENDED\s*[0-9]*\s*[A-Z]*\s*2016|FOR THE\s*(FISCAL)? YEAR ENDED\s*(Commission File Number)?\W?\s*[A-Z]*\s*[0-9]*,\s*2017',filingShort,re.IGNORECASE):
            filing = filing.replace('\n', '').replace('\t', '').replace('\r','').replace('Contents',' ').upper().split('ITEM ')
            break
        
        elif re.search(r'FOR THE FISCAL YEAR ENDED\s*[0-9]*\s*[A-Z]*\s*2018|FOR THE\s*(FISCAL)? YEAR ENDED\s*(Commission File Number)?\W?\s*[A-Z]*\s*[0-9]*,\s*2018',filingShort,re.IGNORECASE):
            d += 1
        
        elif re.search(r'FOR THE FISCAL YEAR ENDED\s*[0-9]*\s*[A-Z]*\s*2017|FOR THE\s*(FISCAL)? YEAR ENDED\s*(Commission File Number)?\W?\s*[A-Z]*\s*[0-9]*,\s*2016',filingShort,re.IGNORECASE):
            d += 1
            
        elif re.search(r'FOR THE FISCAL YEAR ENDED\s*[0-9]*\s*[A-Z]*\s*2015|FOR THE\s*(FISCAL)? YEAR ENDED\s*(Commission File Number)?\W?\s*[A-Z]*\s*[0-9]*,\s*2016',filingShort,re.IGNORECASE):
            d += 1
        else:
            return None

    new_doc = []
    start = []
    stop = []
    # remove characters from filing
    for item in filing:
        new_doc.append(re.sub('\\xa0*|(?<=[7-8])\W?s?','',item))
    for i in range(len(new_doc)):
        if re.search(r'7\s*\W?\.?\s*(AND 7A.)?(COMBINED)?\s*MANAGEMENT\W?\s*S\s*DISCUSSION\s*AND\s*ANALYSIS\s*OF\s*(CONSOLIDATED)?\s*FINANCIAL\s*CONDITION\S?\s*AND\s*RESULTS\s*OF\s*OPERATION\S?',new_doc[i]):
            start.append(i)
        if re.search(r'7\s*\W?\.?\s*MANAGEMENT\W?\s*S\s*DISCUSSION\s*AND\s*ANALYSIS\s*OF\s*RESULTS\s*OF\s*OPERATIONS\s*AND\s*FINANCIAL\s*CONDITION',new_doc[i]):
            start.append(i)
        #if re.search(r'8\s*\W?\w?\.?\s*(CONSOLIDATED)?(COMCAST CORPORATION)?\s*FINANCIAL\s*STATEMENTS\s*AND\s*SUPPLEMENTA\w*\s*DATA',new_doc[i]):
            #stop.append(i)     
        if re.search(r'9\s*\W?\w?\.?\s*CONTROLS\s*AND\s*PROCEDURES',new_doc[i]):
            stop.append(i) 
    
    
#     for i in range(len(new_doc)):
#         if len(stop) == 0 and len(start) > 0:
#             if re.search(r'8\s*\W?\w?\.?\s*FINANCIAL\s*STATEMENTS',new_doc[i]):
#                 stop = [i]
#             if re.search(r'9\s*\W?\w?\.?\s*CONTROLS\s*AND\s*PROCEDURES',new_doc[i]):
#                 stop = [i]
    
    return name,ID,start,stop,d

In [10]:
MDAFCRO_index = []
# go through each company add get the indices of which section to pull the MDA from
for i in range(len(comp)):
    MDAFCRO_index.append(annual_filings(comp.iloc[i].Security,str(comp.iloc[i].CIK)))

In [47]:
MDAFCRO_index

[('3M Company', '0000066740', [11, 29, 31, 42], [16, 64], 1),
 ('Abbott Laboratories', '0000001800', [6, 15], [22], 1),
 ('AbbVie Inc.', '0001551152', [10, 24, 29, 36, 38, 47, 48], [14, 56], 1),
 ('Wyndam Worldwide ', '0001361658', [10, 31], [14, 35], 1),
 ('Accenture plc', '0001467373', [10, 33], [14, 62], 1),
 ('Activision Blizzard', '0000718877', [10, 25, 27, 28, 29, 42], [14, 55], 1),
 ('Adobe Systems Inc', '0000796343', [10, 34, 35], [14, 44], 1),
 ('Advanced Micro Devices Inc',
  '0000002488',
  [10, 25, 26, 27, 36],
  [14, 45],
  1),
 ('Advance Auto Parts', '0001158449', [10, 30], [14, 35], 1),
 ('AES Corp',
  '0000874761',
  [10,
   27,
   29,
   36,
   37,
   38,
   39,
   42,
   43,
   47,
   51,
   53,
   55,
   56,
   59,
   60,
   68,
   78,
   85,
   86],
  [14, 140],
  1),
 ('Affiliated Managers Group Inc', '0001004434', [10, 36], [14, 44], 3),
 ('AFLAC Inc', '0000004977', [10, 39], [14, 65], 1),
 ('Agilent Technologies Inc', '0001090872', [10, 32], [14, 44], 1),
 ('Air Products & Chemicals Inc', '0000002969', [10, 37], [14, 43], 2),
 ('Akamai Technologies Inc', '0001086222', [10, 31], [14, 37], 1),
 ('Alaska Air Group Inc', '0000766421', [10, 31], [14, 36], 1),
 ('Albemarle Corp', '0000915913', [10, 27, 31, 40], [14, 54], 1),
 ('Alexandria Real Estate Equities',
  '0001035443',
  [10, 23, 26, 28, 33, 34, 37, 41, 62],
  [14, 122],
  1),
 ('Alexion Pharmaceuticals', '0000899866', [10, 35, 36], [14, 47], 1),
 ('Align Technology', '0001097149', [10, 38], [14, 48], 1),
 ('Allegion', '0001579241', [10, 35], [14, 42], 1),
 ('Allergan, Plc', '0001578845', [10, 44, 46, 47, 48], [14, 60], 1),
 ('Alliance Data Systems', '0001101215', [2, 12, 13], [2, 17], 1),
 ('Alliant Energy Corp', '0000352541', [10, 34], [14, 47], 1),
 ('Allstate Corp', '0000899051', [10, 35, 36, 71], [14, 97, 99], 1),
 ('Alphabet Inc Class A', '0001652044', [11, 26, 38, 40], [15, 55], 2),
 ('Alphabet Inc Class C', '0001652044', [11, 26, 38, 40], [15, 55], 2),
 ('Altria Group Inc', '0000764180', [10, 30, 65], [14, 93], 2),
 ('Amazon.com Inc.', '0001018724', [10, 46], [14, 68], 1),
 ('Ameren Corp', '0001002910', [11, 60], [15, 124], 1),
 ('American Airlines Group', '0000006201', [10, 24, 28, 32, 65], [15, 115], 1),
 ('American Electric Power', '0000004904', [3, 4, 23], [3, 32], 1),
 ('American Express Co', '0000004962', [2, 11], [2, 22], 1),
 ('American International Group',
  '0000005272',
  [12, 26, 95, 97, 243],
  [16],
  1),
 ('American Tower Corp.', '0001053507', [10, 37], [14, 47], 1),
 ('American Water Works Company Inc',
  '0001410636',
  [10, 25, 29, 30, 43, 45],
  [14, 56],
  1),
 ('Ameriprise Financial', '0000820027', [10, 56], [14, 70], 1),
 ('AmerisourceBergen Corp', '0001140859', [2, 13], [2, 21], 1),
 ('AMETEK Inc.', '0001037868', [9, 22, 23, 26, 32, 36], [13, 60], 1),
 ('Amgen Inc.', '0000318154', [10, 43, 55, 56], [14, 76], 1),
 ('Amphenol Corp', '0000820313', [10, 41], [14, 59], 1),
 ('Anadarko Petroleum Corp', '0000773910', [8, 47], [12, 93], 1),
 ('Analog Devices, Inc.', '0000006281', [10, 40], [14, 57], 1),
 ('ANSYS', '0001013462', [10, 42], [14, 56], 1),
 ('Anthem Inc.', '0001156039', [10, 23, 31, 33, 57, 58, 91], [14, 102], 1),
 ('Aon plc', '0000315293', [10, 37], [14, 50], 1),
 ('A.O. Smith Corp', '0000091142', [10, 37], [14], 1),
 ('Apache Corporation', '0000006769', [2, 4, 6, 7, 9, 21], [2, 43], 1),
 ('Apartment Investment & Management', '0000922864', [3, 28], [2, 3, 50], 1),
 ('Apple Inc.', '0000320193', [10, 32, 41, 43], [14, 62], 1)]

In [ ]:
def MDA(name,ID,start_index,stop_index,doc_num):
    '''This function returns the MDA text of the 10-k filing using the indices provided and the correct document.'''
    # get filings from package
    company = edgar.Company(name,ID)
    tree = company.getAllFilings(filingType = "10-K")
    doc = edgar.getDocuments(tree, noOfDocuments=doc_num+1)
    
    # create the same format used from the function above
    filing = (re.sub('\\xa0|\\n',' ',doc[doc_num]))
    filing = filing.replace('\n', '').replace('\t', '').replace('\r','').replace('Contents',' ').upper().split('ITEM ')
    new_doc = []
    for item in filing:
        new_doc.append(re.sub('\\xa0*|(?<=[7-8])\W?s?','',item))
    
    # find the text using the indices
    MDA_text = []
    
    return name,ID,MDA_text

In [ ]:
MDAFCRO = []
for i in MDAFCRO_index:
    if i != None:
        MDAFCRO.append(MDA(i[0],i[1],i[2],i[3],i[4]))
    else:
        pass